name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MQTT logger using CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libpaho-mqtt-dev \
            libpaho-mqttpp-dev \
            mosquitto-clients
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
